version: '3.8'

networks:
  geotracking-net:
    driver: bridge

services:
  todo-app:
    networks:
      - geotracking-net
    build: ./todo-app
    restart: always
    command: ./todo-app
    ports:
      - 8000:8000
    environment:
      - DB_PASSWORD=postgres
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:latest
    restart: always
    networks:
      - geotracking-net
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 3s
      timeout: 3s
      retries: 5


volumes:
  db-data: { }